services:
  backend:
    container_name: textshare-backend-dev
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    env_file:
      - ./backend/.env

  redis:
    image: redis:7-alpine
    container_name: redis-dev

volumes:
  backend_node_modules: