services:
  backend:
    build: ./backend
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}

  redis:
    image: redis:7-alpine