services:
  backend:
    container_name: textshare-backend-prod
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - prod-network

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    restart: unless-stopped
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge